server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food-court
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include: "*"